/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f446xx.h"
#include "gpio_driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void MX_GPIO_Init(void);

void delay(void)
{
	for (uint32_t i = 0; i < 500000/2; i ++)
	{

	}

}


int main(void)
{
	MX_GPIO_Init();


    /* Loop forever */

	while (1)
	{
		if (GPIO_ReadInputPin(GPIOC, GPIO_PIN_NUM_13) == GPIO_PIN_RESET)
		{
			delay();
			if (GPIO_ReadInputPin(GPIOC, GPIO_PIN_NUM_13) == GPIO_PIN_RESET)
			{
				GPIO_WriteOutputPin(GPIOA, GPIO_PIN_NUM_5, GPIO_PIN_SET);
			}
		}
		if (GPIO_ReadInputPin(GPIOC, GPIO_PIN_NUM_10) == GPIO_PIN_RESET)
		{
			delay();
			if (GPIO_ReadInputPin(GPIOC, GPIO_PIN_NUM_10) == GPIO_PIN_RESET)
			{
				GPIO_WriteOutputPin(GPIOA, GPIO_PIN_NUM_5, GPIO_PIN_RESET);
			}
		}

	}

	return 1;
}

static void MX_GPIO_Init(void)
{
//	Enable the RCC peripheral clocks
	GPIO_PeriClkControl(GPIOA, ENABLE);
	GPIO_PeriClkControl(GPIOC, ENABLE);
	GPIO_Handle_t GPIOA_Onboard_LED_H, GPIOC_Onboard_BTN_H, GPIOC_Ext_LED_H, GPIOC_Ext_BTN_H;
	
	GPIOA_Onboard_LED_H.pGPIOx = GPIOA;
	GPIOA_Onboard_LED_H.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUTPUT;
	GPIOA_Onboard_LED_H.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NUM_5;
	GPIOA_Onboard_LED_H.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPEED_FREQ_LOW;
	GPIOA_Onboard_LED_H.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NOPU;
	GPIOA_Onboard_LED_H.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	GPIO_Init(&GPIOA_Onboard_LED_H);

	// GPIOC_Ext_LED_H.pGPIOx = GPIOC;
	// GPIOC_Ext_LED_H.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUTPUT;
	// GPIOC_Ext_LED_H.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NUM_12;
	// GPIOC_Ext_LED_H.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPEED_FREQ_LOW;
	// GPIOC_Ext_LED_H.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NOPU;
	// GPIOC_Ext_LED_H.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	// GPIO_Init(&GPIOC_Ext_LED_H);

	GPIOC_Ext_BTN_H.pGPIOx = GPIOC;
	GPIOC_Ext_BTN_H.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_INPUT;
	GPIOC_Ext_BTN_H.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NUM_10;
	GPIOC_Ext_BTN_H.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPEED_FREQ_LOW;
	GPIOC_Ext_BTN_H.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NOPU;
	// GPIOC_Ext_BTN_H.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	GPIO_Init(&GPIOC_Ext_BTN_H);

	GPIOC_Onboard_BTN_H.pGPIOx = GPIOC;
	GPIOC_Onboard_BTN_H.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_INPUT;
	GPIOC_Onboard_BTN_H.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NUM_13;
	GPIOC_Onboard_BTN_H.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPEED_FREQ_LOW;
	GPIOC_Onboard_BTN_H.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NOPU;
	// GPIOC_Onboard_BTN_H.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	GPIO_Init(&GPIOC_Onboard_BTN_H);

//	GPIOA_Handler.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_PU;
//	GPIOA_Handler.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_OPENDRAIN;
//	GPIO_Init_Pin.GPIO_PinAltFunMode  = 0x0U;


}
